### ISSUE TITLE
goroutine # [select] waitForUpdate error/crash

### ISSUE THREAD

**Issue by gwindes** [etsy/hound#147]
Have an instance with 200+ repos and it runs through the repo config and then spits out these errors at the end:

```
goroutine 555 [select]:
github.com/etsy/hound/searcher.(*Searcher).waitForUpdate(0xc217eb5fb0, 0x61ce6bd0c0)
        /home/hound/hound-repo/src/github.com/etsy/hound/searcher/searcher.go:153 +0xf4
github.com/etsy/hound/searcher.func·001()
        /home/hound/hound-repo/src/github.com/etsy/hound/searcher/searcher.go:419 +0x15c
created by github.com/etsy/hound/searcher.newSearcher
        /home/hound/hound-repo/src/github.com/etsy/hound/searcher/searcher.go:437 +0xa65

goroutine 557 [select]:
github.com/etsy/hound/searcher.(*Searcher).waitForUpdate(0xc208118630, 0x73fcd422c0)
        /home/hound/hound-repo/src/github.com/etsy/hound/searcher/searcher.go:153 +0xf4
github.com/etsy/hound/searcher.func·001()
        /home/hound/hound-repo/src/github.com/etsy/hound/searcher/searcher.go:419 +0x15c
created by github.com/etsy/hound/searcher.newSearcher
        /home/hound/hound-repo/src/github.com/etsy/hound/searcher/searcher.go:437 +0xa65
```

Any ideas on how to fix this?

**Comment by kellegous** [comment]
Is this the entire output of the crash? All this shows is a couple of goroutines waiting on a channel at the time of the crash.

**Comment by gwindes** [comment]
I found the answer. I was using port 80 and we have an iptable rule to reroute 6080 (Default hound port) to 80 so that's the error I was facing. 

Marked as closed.
